Style/FrozenStringLiteralComment:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/Documentation:
    Enabled: false
Metrics/AbcSize:
    Max: 25
Metrics/MethodLength:
    Max: 20
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'db/migrate/*'